#version: '3'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: 
      - .env
    secrets:
      - db_user
      - db_root_password
      - db_password
    restart: on-failure
    expose:
      - "3306"
  
  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wp-volume:/var/www/wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: 
      - .env
    restart: on-failure
    ports: 
      - "443:443"

  wordpress:
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: 
      - .env
    secrets:
      - db_user
      - db_password
      - wp_admin_user
      - wp_admin_password
      - wp_user
      - wp_user_password
    restart: on-failure
    depends_on:
      - mariadb
    expose:
      - "9000"

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/hongbaki/data/wordpress
      #device: /home/${USER}/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/hongbaki/data/mariadb
      #device: /home/${USER}/data/mariadb

secrets:
   db_user:
     file: ../secrets/db_user.txt
   db_password:
     file: ../secrets/db_password.txt
   db_root_password:
     file: ../secrets/db_root_password.txt
   wp_admin_password:
     file: ../secrets/wp_admin_password.txt
   wp_admin_user:
     file: ../secrets/wp_admin_user.txt
   wp_user_password:
     file: ../secrets/wp_user_password.txt
   wp_user:
     file: ../secrets/wp_user.txt

networks:
    inception:
        driver: bridge




# #version: '3'

# services:
#   nginx:
#     container_name: nginx
#     build:
#       context: requirements/nginx
#       dockerfile: Dockerfile
#     env_file: 
#       - .env
#     depends_on:
#       - wordpress
#     ports: 
#       - "443:443"
#     networks:
#       - inception
#     volumes:
#       - wp-volume:/var/www/wordpress
#     restart: on-failure

#   mariadb:
#     container_name: mariadb
#     networks:
#       - inception
#     volumes:
#       - db-volume:/var/lib/mysql
#     build:
#       context: requirements/mariadb
#       dockerfile: Dockerfile
#       args:
#         DB_NAME: ${DB_NAME}
#         DB_USER: ${DB_USER}
#         DB_PASS: ${DB_PASS}
#         DB_ROOT: ${DB_ROOT}
#     env_file: 
#       - .env
#     # ports:
#     #   - "3306:3306"
#     expose:
#       - "3306"
#     restart: on-failure

#   wordpress:
#     container_name: wordpress
#     build:
#       context: requirements/wordpress
#       dockerfile: Dockerfile
#       args:
#         DB_NAME: ${DB_NAME}
#         DB_USER: ${DB_USER}
#         DB_PASS: ${DB_PASS}
#     env_file: 
#       - .env
#     depends_on:
#       - mariadb
#     networks:
#       - inception
#     volumes:
#       - wp-volume:/var/www/wordpress
#     expose:
#       - "9000"
#     restart: on-failure

# volumes:
#   wp-volume:
#     driver_opts:
#       o: bind
#       type: none
#       device: /home/${USER}/data/wordpress

#   db-volume:
#     driver_opts:
#       o: bind
#       type: none
#       device: /home/${USER}/data/mariadb

# networks:
#     inception:
#         driver: bridge
